### ISSUE TITLE
Implement PartialEq for Vec<u8> and &[u8]?

### ISSUE THREAD

**Issue by sunshowers** [serde-rs/bytes#1]
That would be useful while writing tests, to compare a `Vec<u8>` or a bytestring literal to a `Bytes` or a `ByteBuf` without trying to wrap things up.

**Comment by dtolnay** [comment]
Thanks! Fixed in 82ecabf037dee323d4626c24d1251bd475bf5050 to support comparing with anything that implements AsRef\<[u8]\> on the right-hand side. Released in 0.11.0.
