### ISSUE TITLE
[Help] Serializer/Deserializer for type using variable length encoding scheme

### ISSUE THREAD

**Issue by jinyuanxie** [serde-rs/bytes#4]
For example, I hava a strcut defined as follow:
```rust
pub struct VariableLength(u32);
```

And the field using a variable length encoding scheme, how can I implement Serializer/Deserializer for it?

```text
VaribaleLength <---> Vec<u8>/&[u8]
```

Thanks a lot.

**Comment by dtolnay** [comment]
I moved this to https://github.com/serde-rs/serde/issues/1007 because I don't think it will involve serde_bytes.
